version: '3.8'

services:
  rclone:
    build:
      context: ./rclone
    command: ["/bin/sh", "/copy_fichiers.sh"]
    volumes:
      - shared-data:/drive
    networks:
      - rakuten_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    depends_on:
      - rclone
    volumes:
      - shared-data:/app/drive
      - data:/app/data
    command: /bin/sh -c "sleep 90 && uvicorn api_v3:api --host 0.0.0.0"
    networks:
      - rakuten_network  

  entrainement:
    build:
      context: ./training
      dockerfile: Dockerfile
    command: mlflow server --host 0.0.0.0 --port 5000
    depends_on:
    - rclone
    ports:
    - "5000:5000"
    volumes:
    - shared-data:/app/drive
    
    networks:
    - rakuten_network 

volumes:
  shared-data:
    driver: local
  data:
    driver: local
  data2:
    driver: local

networks:
  rakuten_network:
    driver: bridge